version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "master"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "deps"
      include: "scope" 